# HTTP 服务配置
http:
  bind-address: 127.0.0.1 # 绑定的不安全 IP 地址，设置为 0.0.0.0 表示使用全部网络接口，默认为 127.0.0.1
  bind-port: 8080 # 提供非安全认证的监听端口，默认为 8080
  mode: debug # server mode: release, debug, test，默认 release
  middlewares: recovery,logger # 加载的 gin 中间件列表，多个中间件，逗号(,)隔开

# GRPC 服务配置
grpc:
  bind-address: 0.0.0.0 # grpc 安全模式的 IP 地址，默认 0.0.0.0
  bind-port: 8081 # grpc 安全模式的端口号，默认 8081
